## Keras Basics

In [1]:
import numpy as np
from numpy import genfromtxt


In [2]:
data = genfromtxt('DATA/bank_note_data.txt', delimiter=',')
labels = data[:,4]

In [3]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [4]:
features = data[:,0:4]
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [5]:
X = features
y = labels


In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42) # 33% of data will be used for testing and 67% for training

In [10]:
X_train.max()

17.9274

In [11]:
from sklearn.preprocessing import MinMaxScaler # scaling the data to be between 0 and 1
scaler_object = MinMaxScaler()

In [12]:
scaler_object.fit(X_train) # fit the scaler to the training data and transform the training data
scaled_X_train = scaler_object.transform(X_train)

In [13]:
scaled_X_test = scaler_object.transform(X_test) # transform the test data

In [14]:
from keras.models import Sequential
from keras.layers import Dense

In [15]:
model = Sequential() # create a sequential model
model.add(Dense(4, input_dim=4, activation='relu')) # add a dense layer with 4 neurons and relu activation function
model.add(Dense(8, activation='relu')) # add another dense layer with 8 neurons and relu activation function
model.add(Dense(1, activation='sigmoid')) # add another dense layer with 1 neuron and sigmoid activation function

In [16]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy']) # compile the model with binary crossentropy loss function, adam optimizer and accuracy as the metric

In [17]:
model.fit(scaled_X_train, y_train, epochs=50, verbose=2) # fit the model to the training data

Epoch 1/50
 - 1s - loss: 0.6936 - acc: 0.4385
Epoch 2/50
 - 0s - loss: 0.6921 - acc: 0.5582
Epoch 3/50
 - 0s - loss: 0.6909 - acc: 0.5593
Epoch 4/50
 - 0s - loss: 0.6900 - acc: 0.5615
Epoch 5/50
 - 0s - loss: 0.6889 - acc: 0.5637
Epoch 6/50
 - 0s - loss: 0.6879 - acc: 0.5637
Epoch 7/50
 - 0s - loss: 0.6867 - acc: 0.5626
Epoch 8/50
 - 0s - loss: 0.6851 - acc: 0.5626
Epoch 9/50
 - 0s - loss: 0.6835 - acc: 0.5658
Epoch 10/50
 - 0s - loss: 0.6802 - acc: 0.5658
Epoch 11/50
 - 0s - loss: 0.6754 - acc: 0.6192
Epoch 12/50
 - 0s - loss: 0.6702 - acc: 0.6921
Epoch 13/50
 - 0s - loss: 0.6649 - acc: 0.7650
Epoch 14/50
 - 0s - loss: 0.6584 - acc: 0.7954
Epoch 15/50
 - 0s - loss: 0.6512 - acc: 0.8063
Epoch 16/50
 - 0s - loss: 0.6436 - acc: 0.8194
Epoch 17/50
 - 0s - loss: 0.6347 - acc: 0.8259
Epoch 18/50
 - 0s - loss: 0.6245 - acc: 0.8270
Epoch 19/50
 - 0s - loss: 0.6129 - acc: 0.8292
Epoch 20/50
 - 0s - loss: 0.5998 - acc: 0.8400
Epoch 21/50
 - 0s - loss: 0.5869 - acc: 0.8477
Epoch 22/50
 - 0s - lo

In [18]:
model.predict_classes(scaled_X_test) # predict the classes of the test data

array([[0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
    

In [19]:
## MODEL EVALUATION
model.metrics_names # get the names of the metrics

['loss', 'acc']

In [20]:
from sklearn.metrics import confusion_matrix, classification_report 

In [21]:
predictions = model.predict_classes(scaled_X_test) # predict the classes of the test data
confusion_matrix(y_test, predictions) # get the confusion matrix

array([[244,  13],
       [  9, 187]], dtype=int64)

In [22]:
print(classification_report(y_test, predictions)) # get the classification report

             precision    recall  f1-score   support

        0.0       0.96      0.95      0.96       257
        1.0       0.94      0.95      0.94       196

avg / total       0.95      0.95      0.95       453



In [23]:
model.save('myfirstmodel.h5') # save the model

In [24]:
from keras.models import load_model
newmodel = load_model('myfirstmodel.h5') # load the model
newmodel.predict_classes(scaled_X_test) # predict the classes of the test data

array([[0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
    